sudo: required

services:
  - docker

language: node_js
node_js: 
  - "stable"

script: 
   - cd lykke-log  && npm install
   - cd .. && cd test && npm install
   - cd .. && ./create_test_volume.sh
   - ./create_test_network.sh
   - ./test.sh


